config/routes.rb
Soblog::Application.routes.draw do
  root :to => "articles#index"
  resources :articles do
    member do
       put 'upvote'
       put 'downvote'
    end
    resources :comments 

  end 
  resources :profile
  resources :users
  resource :session
  get '/login' => "sessions#new", :as => "login"
  get '/logout' => "sessions#destroy", :as => "logout"
  resources :categories
end

app/models/article.rb
class Article < ActiveRecord::Base
  validates_presence_of :title, :body

  belongs_to :user
  has_and_belongs_to_many :categories
  has_many :comments

  scope :published, lambda { where("articles.published_at IS NOT NULL") }
  scope :draft, lambda { where("articles.published_at IS NULL") }
  scope :recent, lambda { published.where("articles.published_at > ?", 1.week.ago.to_date) }
  scope :where_title, lambda { |term| where("articles.title LIKE ?", "%#{term}%") }
  
  def long_title
    "#{title} - #{published_at}"
  end

  def published?
    published_at.present?
  end

  def owned_by?(owner)
    return false unless owner.is_a?(User)
    user == owner
  end

  def self.search(search)
    if search
      where('title LIKE ?', "%#{search}%")
    else
      all
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show]
  before_action :authenticate, except: [:index, :show]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.search(params[:search]).paginate(:page => params[:page], :per_page => 4)
    @categories = Category.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @commentsShow = @article.comments.paginate(:page => params[:page], :per_page => 4)
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
    @article = current_user.articles.find(params[:id])
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = current_user.articles.new(article_params)
    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render action: 'show', status: :created, location: @article }
      else
        format.html { render action: 'new' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    @article = current_user.articles.find(params[:id])
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article = current_user.articles.find(params[:id])
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end


  def upvote()
    @article = Article.find(params[:id])
    respond_to do |format|
    if @article.sum != nil  
      @article.sum = @article.sum + params[:upvote].to_i
    else
      @article.sum = params[:upvote].to_i
    end
      if @article.update(:sum => @article.sum)
        format.html { redirect_to root_path, notice: 'Thank you for you upvote.' }
        format.json { head :no_content }
      end
    end
  end

  def downvote()
     @article = Article.find(params[:id])
     respond_to do |format|
      if @article.sum != nil  
        @article.sum = @article.sum + params[:downvote].to_i
      else
        @article.sum = params[:downvote].to_i
      end
      if @article.update(:sum =>  @article.sum)
        format.html { redirect_to root_path, notice: 'Thank you for you downvote.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :location, :excerpt, :body, :published_at, :category_ids => [])
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<%= div_for article do %>
  <h3>
    <p style="font-size: 25px; color: cornflowerblue;">
      <%= article.title %>
    </p>
  </h3>
  <%= simple_format article.body %>

  <% if article.owned_by? current_user %>
      <span class='actions'>
        <%= link_to "Edit", edit_article_path(article), class: 'btn btn-mini btn-info' %>

        <%= link_to 'Delete', article, method: :delete, confirm: 'Are you sure?', class: 'btn btn-mini btn-danger' %>

      </span>
    <% end %>
<% end %>

app/views/articles/_form.html.erb
<%= bootstrap_form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, hide_label: true, placeholder: "Title"%>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location, hide_label: true, placeholder: "Location" %>
  </div>
  
  <div class="field">
    <%= f.label "Categories" %><br />
    <% Category.all.each do |category| %>
      <%= check_box_tag 'article[category_ids][]', category.id,
        @article.category_ids.include?(category.id), id: dom_id(category) %>
        <%= label_tag dom_id(category), category.name, class: "check_box_label" %>
      <% end %>
    </div>
  <div class="field">
    <%= f.label :excerpt %><br>
    <%= f.text_field :excerpt, hide_label: true, placeholder: "Excerpt"%>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body, hide_label: true, placeholder: "Body"%>
  </div>
  <div class="field">
    <%= f.label :published_at %><br>
    <%= f.datetime_select :published_at, hide_label: true, placeholder: "Published At" %>
  </div>
  <div class="actions">
    <%= submit_or_cancel(f) %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<div class="container">
	<div class="col-md-8">
		<div class="page-header">
			<div class="row">
				
				<div class="col-sm-9"><h1>Articles</h1></div>
				<div class="col-sm-3">
					<%= link_to new_article_path, class: "btn btn-default" do %>
	   					<span class="glyphicon glyphicon-chevron-right"></span> New Article
					<% end %>
				</div>
				
			</div>
		</div>
		
		<% @articles.each do |article| %>
			<div class="row" style="margin-bottom: 30px;">
				<div class="col-xs-1" >
   					<%= form_tag upvote_article_path(article), :method => 'PUT' do %>
					  <div class="input-group">
					  	<%= hidden_field_tag :upvote, 1 %>
					  	<span class="input-group-btn">
					    	 <%= button_tag(type: "submit", class: "btn btn-default") do %>
		   						<span class="glyphicon glyphicon-thumbs-up"></span>
							<% end %>
					     </span>
					</div>
		   	 		<% end %>

		   	 		
					<%= form_for article do |f| %>
						 <% if article.sum != nil %> 
							<%= f.text_field :sum, readonly:true, size:1%>
						 <% else %>
						 	<%= f.text_field :sum, readonly:true, size:1,  :value => '0'%>
						<% end %>
					<% end %>
				

					<%= form_tag downvote_article_path(article), :method => 'PUT' do %>
						  <div class="input-group">
						  	<%= hidden_field_tag :downvote, -1 %>
						  	<span class="input-group-btn">
						    	 <%= button_tag(type: "submit", class: "btn btn-default") do %>
			   						<span class="glyphicon glyphicon-thumbs-down"></span>
								<% end %>
						     </span>
						</div>
			   	 		<% end %>
				</div>
				
				<div class="col-xs-11">
					<p><span class="glyphicon glyphicon-time"></span> Published at: <%= article.created_at %>
					</p>

					<p><span class="glyphicon glyphicon-time"></span> Posted By:  <%= link_to article.user.try(:email), article.user.try(:profile)%>
					</p>

					<% if article.categories.count > 0 %>

						<p><span class="glyphicon glyphicon-time"></span> Categorys:

					<% end %>

			   		<% article.categories.each do |category| %>

						 <%= link_to category.name, category %>,
			   		<% end %>

			   		</p> 

     				<p style="font-size: 25px; color: cornflowerblue; ">
						<%= article.title %> <small style="color:black; font-size: small;">(<%= article.comments.count %>  <% if article.comments.count > 1  or article.comments.count == 0%> Comments <% else %> Comment <% end %>)</small>
					</p>

					</br>
					<%= article.body %>
					<br>
					<br>

					<%= link_to article, class: "btn btn-default" do %>
	   					 <span class="glyphicon glyphicon-chevron-right"></span> Read More
					<% end %>

					<% if article.comments.count > 1 %> 
						<%= link_to "#", id: "comments-link", class: "btn btn-default" do %>
		   					 <span class="glyphicon glyphicon-chevron-right"></span> Top Comments
						<% end %>
					<% end %>

					<section id="comments-section"> 

						<div class="row">
							<ol id="comments">
								<% article.comments.first(3).each do |comment| %>
									<br>
									<strong><%= comment.name %></strong>
									<blockquote>
								  		<p><%= comment.body %></p>
								  	</blockquote>
								<% end %>
						  	</ol> 
						</div>
					</section>
				</div>
			</div>
			
		<% end %>

		<div class="flickr_pagination">
		    <div class="page_info">
		     	 <%= page_entries_info @articles %>
		    </div>
		    <%= will_paginate @articles, :container => false %>
		</div>	
	</div>

	<div class="col-md-4">
	    <!-- Blog Search Well -->
	    <div class="well">
	        <h4>Blog Search</h4>
	        <%= form_tag root_path, :method => 'get' do %>
			  <div class="input-group">
			  	<%= text_field_tag :search, params[:search], placeholder: "", :class => "form-control" %>
			  	<span class="input-group-btn">
			    	 <%= button_tag(type: "submit", class: "btn btn-default") do %>
   						<span class="glyphicon glyphicon-search"></span>
					<% end %>
			     </span>
			</div>
			    <% end %>
    	</div>

		<!-- Blog Categories -->
	    <div class="well">
	        <div class="col-sm-6"><h4>Categories</h4></div>
	        <div class="col-sm-6"><%= link_to new_category_path, class: "btn btn-default" do %>
	   			<span class="glyphicon glyphicon-chevron-right"></span> New Category
			<% end %></div>
	        <div class="row">
	            <div class="col-xs-11 col-xs-offset-1">
	                <% @categories.first(3).each do |categories| %> 
				    	<br>
						<%= link_to categories.name, categories %>
				   	<% end %>
	            </div>
	        </div>
	    </div>
	</div>
</div>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<%= render @article %>

<div id="details">
	Published on <%= @article.created_at %> by <%= @article.user.try(:email) %> 
</div>

<h3>  <%= link_to "Comments", "#", id: "comments-link" %> <small style="color:black; font-size: small;"> (<%= @article.comments.count %>  <% if @article.comments.count > 1  or @article.comments.count == 0%> Comments<% else %> Comment<% end %>)</small> </h3>

<section id="commentsection"> 

	<div class="row">
	  	<%= render @commentsShow %>
	</div>

	<div class="flickr_pagination">
	    <div class="page_info">
	     	 <%= page_entries_info @commentsShow %>
	    </div>
	    <%= will_paginate @commentsShow, :container => false %>
	</div>	

	<br>
	<h3> Add a Comment </h3>
	<%= render :file => 'comments/new' %>
</section>