config/routes.rb
Soblog::Application.routes.draw do
  root :to => "articles#index"
  resources :articles do
    member do
       put 'upvote'
       put 'downvote'
    end
    resources :comments 

  end 
  resources :profile
  resources :users
  resource :session
  get '/login' => "sessions#new", :as => "login"
  get '/logout' => "sessions#destroy", :as => "logout"
  resources :categories
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>

  <nav class="navbar navbar-default navbar-fixed" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/"><b>SOBLOG</b></a>
    </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
         <li><%= link_to "Home", root_path %></li> 
         <% if logged_in? %>
          <li><%= link_to "All Categories", categories_path %></li> 
          <li><%= link_to "Edit Profile", edit_profile_path(current_user) %></li> 
          <li><%= link_to "Account Details", edit_user_path(current_user) %></li> 
          <li><%= link_to "Logout", logout_path %></li>
        <% else %>
           <li><%= link_to "Login", login_path %></li>
           <li><%= link_to "Sign Up", '/users/new' %></li>
        <% end %>
      </ul>
      </div> 
    
   </div><!-- /.container-fluid -->
</nav>

<body>
  <div class="container"
    <div id="main">
      <%= content_tag(:p, notice, class: 'notice') if notice.present? %>
      <%= content_tag(:p, alert, class: 'alert') if alert.present? %>
      <%= yield %>
    </div>
    <div id="footer" class="container col-xs-offset-5" style="padding-bottom: 20px;">
      <br>
      The social, sharing blog</a>
  </div>
</div>
</body>
</html>